### ISSUE TITLE
Sort output of paths

### ISSUE THREAD

**Issue by ineiti** [Ubique-OSS/springboot-swagger3#7]
It seems to me that the output of the paths in the yaml file is not constant. This makes it difficult to verify if a current yaml is up-to-date or not.

Proposition: sort the paths alphabetically.

Edge-case: given `[ /v1/, /v1/exposed]`, the `/v1/` should come first.

**Comment by ubamrein** [comment]
The output yaml should be in order of appearance in the (compiled) class since it is using a `LinkedHashMap` internally:
```java  /**
     * Constructs an empty insertion-ordered {@code LinkedHashMap} instance
     * with the default initial capacity (16) and load factor (0.75).
     */
    public LinkedHashMap() {
        super();
        accessOrder = false;
    }
```
