### ISSUE TITLE
support hiding model property

### ISSUE THREAD

**Issue by kistlers** [Ubique-OSS/springboot-swagger3#8]
We should be able to support the `@ApiModelProperty` annotation. Especially the feature to hide properties using `@ApiModelProperty(hidden = true)`. See: https://docs.swagger.io/swagger-core/v1.5.0/apidocs/io/swagger/annotations/ApiModelProperty.html#hidden()

according to the documentation of the swagger-annotations package, any property that should be hidden using `@ApiModelProperty` must reside inside a model annotated by `@ApiModel`. Might be an idea to recreate this idea.

**Comment by ubamrein** [comment]
We already  respect `@JsonIgnore` for the purpose of hiding fields in the API. If fields are not required, we  can mark them as such (default) and add documentation.
